#!/bin/bash

# Create a new Angular application
ng new movebank-explorer-web --directory ./

Which stylesheet format would you like to use?
Sass (SCSS)     [ https://sass-lang.com/documentation/syntax#scss ]

Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No

# Start the development server
ng s -o

mkdir -p public/data
touch public/data/datasets.json

# Generate a new component [https://angular.dev/cli/generate/class]
ng generate i core/models/dataset.model
ng generate s core/services/dataset.service

ng generate c features/dataset-catalog
ng generate c features/dataset-detail
ng generate c features/powered

# TODO
ng generate g core/guards/match
ng generate g core/guards/activate

# Directory Structure
movebank-explorer-web/
├── src/
│   ├── app/
│   │   ├── core/
│   │   │   ├── models/
│   │   │   │   └── dataset.model.ts
│   │   │   └── services/
│   │   │       └── dataset.service.ts
│   │   ├── features/
│   │   │   ├── catalog/
│   │   │   │   ├── catalog.component.ts
│   │   │   │   ├── catalog.component.html
│   │   │   │   └── catalog.component.scss
│   │   │   └── dataset-detail/
│   │   │       └── dataset-detail.component.ts
│   │   ├── shared/
│   │   │   ├── components/
│   │   │   │   ├── dataset-card/
│   │   │   │   │   ├── dataset-card.component.ts
│   │   │   │   │   ├── dataset-card.component.html
│   │   │   │   │   └── dataset-card.component.scss
│   │   │   │   └── navbar/
│   │   │   │       ├── navbar.component.ts
│   │   │   │       └── navbar.component.scss
│   │   │   └── styles/
│   │   │       ├── _variables.scss
│   │   │       ├── _mixins.scss
│   │   │       └── global.scss
│   │   ├── app.component.ts
│   │   ├── app.component.html
│   │   └── app.routes.ts
│   ├── index.html
│   └── main.ts
├── public/
│   └── _redirects
└── angular.json     

# DATA
    src/
└── public/
    └── data/
        └──  datasets.json                  <-- list

# Workers *(Live API returned no data or blocked by CORS policy.)
# install wrangler@4.120.0
npx wrangler login

# crete proxy.conf.json
mkdir move-proxy
cd move-proxy
npx wrangler init

npm install --save-dev @cloudflare/workers-types